[project]
name = "cnn-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.31.0",
    "matplotlib>=3.9.4",
    "notebook>=7.5.0",
    "numpy>=2.0.2",
    "tinygrad>=0.11.0",
]
